name: CMake
on: [push]

jobs:
  build_juliet:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
    
      - name: Get Juliet
        shell: bash
        run: curl --output 2017-10-01-juliet-test-suite-for-c-cplusplus-v1-3.zip --url https://samate.nist.gov/SARD/downloads/test-suites/2017-10-01-juliet-test-suite-for-c-cplusplus-v1-3.zip

      - name: Unzip Juliet
        shell: bash
        run: unzip 2017-10-01-juliet-test-suite-for-c-cplusplus-v1-3.zip
       
      - name: Configure Juliet
        run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
   
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Juliet
          path: compile_commands.json
          retention-days: 3

