name: CMake
on: [push]

jobs:
  build_juliet:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get Juliet
        shell: bash
        run: curl --output $GITHUB_WORKSPACE/2017-10-01-juliet-test-suite-for-c-cplusplus-v1-3.zip --url https://samate.nist.gov/SARD/downloads/test-suites/2017-10-01-juliet-test-suite-for-c-cplusplus-v1-3.zip

      - name: Unzip Juliet
        shell: bash
        run: unzip $GITHUB_WORKSPACE/2017-10-01-juliet-test-suite-for-c-cplusplus-v1-3.zip
        
      - name: List Juliet
        shell: bash
        run: ls

      - name: Configure Juliet
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build
    
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Juliet
          path: $GITHUB_WORKSPACE/build/compile_commands.json
          retention-days: 3

